keys:
  - &connor age10ww6jvrdvd2pkqt5ypszdydr72guqhtva2suwgdq0034ayz78grshz38f5
  - &odin age1m6xmlm0j7pc53z2xn44cus3x2fzqhjh6vdy9urhv8w0zx9xphptsx8y87n
creation_rules:
  - path_regex: ^sops/.*\.ya?ml$
    key_groups:
      - age:
        - *connor
        - *odin
  - path_regex: configuration/hosts/homelab/secrets.yml$
    key_groups:
      - age:
        - *connor
        - *odin

