{ lib, ... }:
let
  devicePath = "/dev/sda";
  diskId = "odin-root";
in
{
  # DO NOT EDIT THIS FILE AFTER INSTALLATION.
  # Changing the partition layout on a live system can render it unbootable.

	boot = {
		loader = {
			efi.canTouchEfiVariables = lib.mkDefault false;
			grub.efiSupport = lib.mkDefault true;
			grub.efiInstallAsRemovable = lib.mkDefault true;
		};
	};

  disko.devices = {
    disk = {
      main = {
        name = "main-${diskId}";
        type = "disk";
        device = devicePath;
        content = {
          type = "gpt";
          partitions = {
            boot = {
              size = "1M";
              type = "EF02"; # for grub MBR
              priority = 1;
            };

            ESP = {
              size = "512M";
              type = "EF00";
              content = {
                type = "filesystem";
                format = "vfat";
                mountpoint = "/boot";
                mountOptions = [ "nofail" ];
              };
            };

            root = {
              size = "100%";
              content = {
                type = "filesystem";
                format = "ext4";
                mountpoint = "/";
              };
            };
          };
        };
      };
    };
  };
}

