-- Generated by wallust. Do not edit by hand.
return {
  image = "{{wallpaper}}",
  active_border = "rgba({{color4 | strip}}ff)",
  inactive_border = "rgba({{color8 | strip}}ff)",
  background_color = "rgba({{background | strip}}ff)",
  border_active = "rgba({{color4 | strip}}ff)",
  border_inactive = "rgba({{color8 | strip}}ff)",
  border_locked_active = "rgba({{color5 | strip}}ff)",
  border_locked_inactive = "rgba({{color0 | strip}}ff)",
}
